// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Lsp7Nwi8kQXmlxdjI8lfmrEtgOdnTY4',
    appId: '1:836339739706:web:b7e5c386dfd58bf5205903',
    messagingSenderId: '836339739706',
    projectId: 'socialred-3f416',
    authDomain: 'socialred-3f416.firebaseapp.com',
    storageBucket: 'socialred-3f416.appspot.com',
    measurementId: 'G-35SLE1C0J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApfefGhP-CUTxFNntbamnFxB-qYZqcAIM',
    appId: '1:836339739706:android:cee2a0fdb3b34262205903',
    messagingSenderId: '836339739706',
    projectId: 'socialred-3f416',
    storageBucket: 'socialred-3f416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpxqKeRwZJMPZZuWGdQNXOpdZB9f_PCFI',
    appId: '1:836339739706:ios:b23a0e5d3f7ec63d205903',
    messagingSenderId: '836339739706',
    projectId: 'socialred-3f416',
    storageBucket: 'socialred-3f416.appspot.com',
    iosClientId: '836339739706-hiaupsdi9aajaqnqnq2m3p9lsd81efoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.rdSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpxqKeRwZJMPZZuWGdQNXOpdZB9f_PCFI',
    appId: '1:836339739706:ios:85abd6627947cc50205903',
    messagingSenderId: '836339739706',
    projectId: 'socialred-3f416',
    storageBucket: 'socialred-3f416.appspot.com',
    iosClientId: '836339739706-lio7s8glu10ua5ekm7li418r08in8m5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.rdSocial.RunnerTests',
  );
}
